logging:
  config: classpath:logback-spring.xml
  path: logs/rule-engine-monitor/log
  level.root: info

server:
  port: 8011

spring:
  application:
    name: rule-engine-monitor
  security:
    user:
      name: admin
      password: admin

