logging:
  config: classpath:logback-spring.xml
  path: logs/rule-engine-monitor/log
  level.root: info

server:
  port: 8011

spring:
  application:
    name: rule-engine-monitor
  security:
    user:
      name: admin
      password: admin

  #邮箱
  mail:
    host:
    username:
    password:
    port: 465
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.ssl.enable: true
  #邮件预警
  boot:
    admin:
      notify:
        mail:
          to:
          from:

#配置文件加密ENC()
jasypt:
  encryptor:
    password:
